### ISSUE TITLE
[bug-report] crash with large ad download on FreeBSD

### ISSUE THREAD

**Issue by TLINDEN** [TLINDEN/kleingebaeck#72]
Command:
```
kleingebaeck -u 127291161 -o bak2 -c kleinanzeigen.conf -d
```

Config;
```toml
adnametemplate = "{{.Slug}}-{{.ID}}"
```

```default
2024-02-09T09:55.10 CET DEBUG: got cookies? /home/scip/dev/kleingebaeck/fetch.go: 82
    program_info:
        go_version: go1.21.1
        pid: 41268
    cookies: []
panic: runtime error: slice bounds out of range [:-1]

goroutine 15813 [running]:
github.com/tlinden/yadu.(*Handler).appendAttr(0x86c13b960, 0x870180?, {{0x8c957b, 0x5}, {{}, 0x3, {0x839100, 0x86c87e080}}})
        /home/scip/go/pkg/mod/github.com/tlinden/yadu@v0.1.1/handler.go:216 +0x617
github.com/tlinden/yadu.(*Handler).Handle.func1({{0x8c957b, 0x5}, {{}, 0x3, {0x839100, 0x86c87e080}}})
        /home/scip/go/pkg/mod/github.com/tlinden/yadu@v0.1.1/handler.go:81 +0x105
log/slog.Record.Attrs({{0xc169c22b878e58e3, 0xed93a073c, 0xc62740}, {0x8cddf3, 0xb}, 0xfffffffffffffffc, 0x8026e5, {{{0x8c957b, 0x5}, {{...}, ...}}, ...}, ...}, ...)
        /usr/lib/go-1.21/src/log/slog/record.go:84 +0xc4
github.com/tlinden/yadu.(*Handler).Handle(_, {_, _}, {{0xc169c22b878e58e3, 0xed93a073c, 0xc62740}, {0x8cddf3, 0xb}, 0xfffffffffffffffc, 0x8026e5, ...})
        /home/scip/go/pkg/mod/github.com/tlinden/yadu@v0.1.1/handler.go:77 +0x1e5
log/slog.(*Logger).log(0x86c198550, {0x9845d8, 0xc91b60}, 0xfffffffffffffffc, {0x8cddf3, 0xb}, {0x86c490f08, 0x6, 0x6})
        /usr/lib/go-1.21/src/log/slog/logger.go:225 +0x1e4
log/slog.Debug({0x8cddf3?, 0x877363258?}, {0x86c490f08?, 0xc91b60?, 0x86c1fa000?})
        /usr/lib/go-1.21/src/log/slog/logger.go:250 +0x96
main.ScrapeImages.func1()
        /home/scip/dev/kleingebaeck/scrape.go:203 +0x425
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/scip/go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /home/scip/go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:72 +0x96
```

**Comment by TLINDEN** [comment]
Fixed in yadu, updated yadu to v0.1.2.
